name: Build Multiple RN versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
        react-native-version: [0.64, 0.63, 0.62, 0.61]
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install RN Version
        run:
          cd example && yarn upgrade react-native@${{
          matrix.react-native-version }}

      - name: Build library and example app
        run: yarn
