
# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator Test

on:
  issues:
    types: [opened]
  workflow_call:
    inputs:
      label:
        required: true
        type: string

jobs:
  call-workflow-passing-data:
    uses: amplitude/Amplitude-TypeScript/.github/workflows/jira-issue-create.yml@github-template
    with:
      label: "RN"
    secrets: inherit